product_import_app/models/__init__.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

from .product import Product
from .csv_file import CsvFile

product_import_app/models/csv_file.py
"""Product import app CSV table."""
from datetime import datetime

from product_import_app.models import db


class CsvFile(db.Model):
    """Table to store CSV file info."""

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode, nullable=False)
    uuid = db.Column(db.Unicode, nullable=False, unique=True)
    status = db.Column(db.Unicode)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    modified_at = db.Column(
        db.DateTime, default=datetime.utcnow,
        onupdate=datetime.utcnow, nullable=False
    )

product_import_app/models/product.py
"""Product import app Products table."""
from datetime import datetime

from product_import_app.models import db


class Product(db.Model):
    """Table to store products info."""

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode, nullable=False)
    sku = db.Column(db.Unicode, nullable=False, unique=True)
    description = db.Column(db.Unicode)
    is_active = db.Column(db.Boolean, nullable=False, default=True)
    is_deleted = db.Column(db.Boolean, nullable=False, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)
    modified_at = db.Column(
        db.DateTime, default=datetime.utcnow,
        onupdate=datetime.utcnow, nullable=False
    )

product_import_app/__init__.py
"""Product import app entry point."""
from flask import Flask
from flask_restful import Api
from flask_wtf.csrf import CsrfProtect

from celery import Celery

from product_import_app.api import configure_api
from product_import_app.models import db
from product_import_app.views import main

app = Flask(__name__)
app.config.from_object('product_import_app.config.default')

db.app = app
db.init_app(app)

csrf_protect = CsrfProtect(app)
app.register_blueprint(main)
api_manager = Api(app)
configure_api(api_manager)

celery = Celery(app.name, broker=app.config['CELERY_BROKER_URL'])
celery.conf.update(app.config)

product_import_app/api/__init__.py
from .product import ProductApi
from .product_import import ProductImportApi


def configure_api(api_manager):
    """Configure API url endpoints."""
    api_manager.add_resource(
        ProductApi,
        '/api/product',
        '/api/product/',
        '/api/product/<int:page>',
        '/api/product/<string:sku>',
    )
    api_manager.add_resource(
        ProductImportApi,
        '/api/product-import',
        '/api/product-import/'
    )

product_import_app/tasks/__init__.py
from .product_import import product_import

product_import_app/views/__init__.py
from .main import main

product_import_app/views/main.py
"""Product import main view."""
from flask import Blueprint, render_template, request, url_for
from sqlalchemy import desc, or_

from product_import_app.models import CsvFile, Product

main = Blueprint('main', __name__)


@main.route('/')
@main.route('/<int:page>')
def home(page=None):
    """Render HomePage with upload Ux, and list items."""
    products = Product.query.order_by(Product.id).paginate(page, 20, False)
    next_url = url_for('main.home', page=products.next_num) \
        if products.has_next else None
    prev_url = url_for('main.home', page=products.prev_num) \
        if products.has_prev else None
    template_args = {
        'next_url': next_url,
        'prev_url': prev_url,
        'products': products.items,
        'num_of_results': len(products.items),
        'page_title': 'Products list'
    }
    return render_template('home.html', **template_args)


@main.route('/search')
def search():
    """Search the DB records matching the keyword."""
    keyword = request.args.get('keyword')
    products = Product.query.filter(
        or_(
            Product.name.ilike('%{}%'.format(keyword)),
            Product.sku.ilike('%{}%'.format(keyword)),
            Product.description.ilike('%{}%'.format(keyword))
        )
    ).all()
    return render_template('home.html', **{
        'products': products,
        'num_of_results': len(products),
        'page_title': 'Search results'
    })


@main.route('/status')
def product_import_status():
    """Return the status of all the csv imports."""
    csv_records = CsvFile.query.order_by(desc(CsvFile.created_at)).all()
    return render_template('status.html', **{'csv_records': csv_records})

product_import_app/templates/home.html
<!DOCTYPE html>
<html>
<head>
	<title>Product Importer</title>
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="static/css/bootstrap/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="static/css/styles.css">
</head>
<body>
	<div id="main-title"><h1> <a href="{{url_for('main.home')}}">Product Importer</a> </h1></div>
	<div class="container add-import-product">
		{% if page_title == 'Products list' %}
			<div class="row">
				<div id="upload" class="col-md-6 action-col">
					Import a Product <input type="file" name="csv-file" accept=".csv" />
					<br>
					<a href="{{url_for('main.product_import_status')}}" target="_blank">Click here to know the status</a>
				</div>
				<div id="addProduct" class="col-md-6 action-col">
					<button class="btn btn-success" id="add-btn">Add a Product</button>
				</div>
			</div>
		{% endif %}
	</div>
	<div class="container">
		<div id="search-box">
			<form action="/search" method="get">
				<input type="text" name="keyword" placeholder="Search for products" />
				<input type="submit" id="search-btn" class="btn btn-primary" />
			</form>
		</div>
		<div id='products-list'>
			<h4>{{page_title}}</h4>
			<i>Displaying {{num_of_results}} results</i>
			<table>
				<tr>
					<th>No.</th>
					<th>Name</th>
					<th>SKU</th>
					<th>Description</th>
					<th>Active</th>
					<th>Actions</th>
				</tr>
				{% for product in products %}
					<tr>
						<td>{{loop.index}}</td>
						<td>{{product.name}}</td>
						<td>{{product.sku}}</td>
						<td>{{product.description}}</td>
						<td>{{product.is_active}}</td>
						<td class="action-btns">
							<span class="btn btn-info edit-btn">Edit</span>
							<span class="btn btn-danger delete-btn">Delete</span>
						</td>
					</tr>
				{% endfor %}
			</table>
			<div class="navigation">
				{% if prev_url %}
					<a href="{{prev_url}}">Prev</a>
				{% endif %}
				{% if next_url %}
					<a href="{{next_url}}">Next</a>
				{% endif %}
			</div>
		</div>
		<!-- Edit-Modal -->
		<div id="addEditModal" class="modal fade" role="dialog">
			<div class="modal-dialog">

		    <!-- Modal content-->
		    <div class="modal-content">
				<div class="modal-header">
					<h4 class="modal-title addEditModal-title">Product</h4>
				</div>
				<div class="modal-body product-info">
					<div><span>SKU</span><input type="text" name="product-sku"/></div>
					<div><span>Name</span><input type="text" name="product-name" /></div>
					<div><span>Description</span><textarea name="product-description"></textarea></div>
					<div><span>Is Active</span><input type="checkbox" name="product-active"></div>
				</div>
				<div class="modal-footer">
					<div class="error-msg alert alert-warning alert-dismissible fade"></div>
					<button type="button" class="btn btn-primary save-btn">Save</button>
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>

			</div>
		</div>
	</div>
	<script type="text/javascript" src="static/js/jquery/jquery.min.js"></script>
	<script type="text/javascript" src="static/js/bootstrap/bootstrap.min.js"></script>
	<script type="text/javascript" src="static/js/script.js"></script>
</body>
</html>

product_import_app/templates/status.html
<!DOCTYPE html>
<html>
<head>
	<title>Product Import Status</title>
	<link rel="stylesheet" type="text/css" href="static/css/bootstrap/bootstrap.min.css">
	<link rel="stylesheet" type="text/css" href="static/css/styles.css">
</head>
<body>
	<div class="container">
		<h4>Product Import Status</h4>
		<table>
			<tr>
				<th>No.</th>
				<th>Name</th>
				<th>UUID</th>
				<th>Created On</th>
				<th>Status</th>
			</tr>
			{% for csv in csv_records %}
				<tr>
					<td>{{loop.index}}</td>
					<td>{{csv.name}}</td>
					<td>{{csv.uuid}}</td>
					<td>{{csv.created_at}}</td>
					<td>
						{% if csv.status == 'COMPLETED' %}
							<a href="{{url_for('main.home')}}">{{csv.status}}</a>
						{% else %}
							{{csv.status}}
						{% endif %}
					</td>
				</tr>
			{% endfor %}
		</table>
	</div>
</body>
</html>